const params=new URLSearchParams(location.search);const studentId=Number(params.get('student_id')||getSelectedStudent());let assessmentId=Number(params.get('assessment_id')||1);const conceptId=Number(params.get('concept_id')||0);setStudent(studentId);const el=id=>document.getElementById(id);let questions=[],index=0,startedAt=Date.now(),answers=[],assessment=null;
function conceptName(id){return ({1:'Basic Linear Equations',2:'Variables on Both Sides',3:'Transposition',4:'Algebraic Expressions',20:'Whole Numbers & Operations',21:'Fractions & Decimals',22:'Perimeter & Area',23:'Integers',24:'Fractions & Decimals',25:'Ratio & Proportion',26:'Rational Numbers',27:'Algebraic Expressions',28:'Simple Equations',29:'Linear Equations',30:'Exponents & Powers',31:'Comparing Quantities',32:'Number Systems',33:'Polynomials',34:'Coordinate Geometry'}[id]||'Learning concept')}
function render(){
 const q=questions[index];
 const domain=conceptName(q.concept_id);
 el('content').innerHTML=`<div class="page-head"><div><div class="eyebrow">${esc((assessment.assessment_type||'diagnostic').replaceAll('_',' '))}</div><h1>${assessment.assessment_type==='targeted'?'Targeted Practice':assessment.assessment_type==='reassessment'?'Targeted Reassessment':'MCQ Session'}</h1><p>${assessment.assessment_type==='targeted'?'Practice the concept identified from your previous responses.':assessment.assessment_type==='reassessment'?'Let’s check your understanding of the same concept again.':`${esc(assessment.topic_name||'Your class curriculum')} · questions are selected using your recorded progress.`}</p></div><a class="btn btn-secondary" href="student.html?student_id=${studentId}">Exit</a></div><div class="card card-pad"><div class="question-stepper" aria-label="Question progress">${questions.map((_,i)=>`<span class="question-step ${i<index?'done':i===index?'current':''}">${i<index?'✓':i===index?'':i+1}</span>${i<questions.length-1?'<span class="question-connector"></span>':''}`).join('')}</div><div class="progress-meta"><span>Question ${index+1} of ${questions.length}</span><span>${esc(q.difficulty)}</span></div><div class="question-domain"><span>Specific domain</span><strong>${esc(domain)}</strong></div><h2 class="question-text">${formatQuestionText(q.question_text)}</h2><div class="question-options">${(q.options||[]).map((option,i)=>`<div class="option" data-option-index="${i}"><input type="radio" name="answer" id="opt-${i}" value="${esc(option)}"><label for="opt-${i}">${formatQuestionText(option)}</label></div>`).join('')}</div><div id="attempt-feedback"></div><div class="hero-actions" style="justify-content:space-between"><button class="btn btn-secondary" id="prev">Previous</button><button class="btn btn-primary" id="next">${index===questions.length-1?'Finish':'Next question'}</button></div></div>`;
 el('prev').disabled=index===0;
 el('prev').onclick=()=>{index=Math.max(0,index-1);render()};
 document.querySelectorAll('.option').forEach(option=>option.addEventListener('click',()=>{const radio=option.querySelector('input');radio.checked=true;document.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));option.classList.add('selected')}));
 const prior=answers[index];if(prior){const selected=document.querySelector(`input[name="answer"][value="${CSS.escape(prior.answer)}"]`);if(selected){selected.checked=true;selected.closest('.option')?.classList.add('selected')}}
 el('next').onclick=submitCurrent
}

function formatQuestionText(value){
 const safe=esc(value||'');
 return safe.replace(/(√\d+|\d+²|\d+³|[a-zA-Z]²|[a-zA-Z]³)/g,'<span class="math-symbol">$1</span>');
}

function answerExplanation(item){
 const q=item.question||{};
 const text=(q.question_text||'').toLowerCase();
 const correct=q.correct_answer||item.result?.correct_answer||'';
 if(text.includes('perimeter of a square')) return `A square has 4 equal sides, so perimeter = 4 × side. Here, 4 × 6 cm = ${correct}.`;
 if(text.includes('area of a rectangle')) return `Rectangle area = length × width. Here, 5 × 4 = ${correct}.`;
 if(text.includes('percent') || text.includes('%')) return `Convert the percentage to a decimal and multiply by the given amount. The correct result is ${correct}.`;
 if(text.startsWith('simplify:')) return `Combine like terms and keep the constant term unchanged. This gives ${correct}.`;
 if(text.includes('ratio')) return `Simplify the ratio by dividing both parts by their common factor. The result is ${correct}.`;
 if(text.includes('coefficient')) return `The coefficient is the number multiplying the variable. Here, the coefficient is ${correct}.`;
 if(text.includes('x-coordinate')) return `The x-coordinate is the first number in an ordered pair (x, y). The correct answer is ${correct}.`;
 if(text.includes('y-axis')) return `A point on the y-axis has x = 0. The correct answer is ${correct}.`;
 if(/^solve:/i.test(q.question_text||'')) return `Work through the equation by isolating the variable on one side. The correct solution is ${correct}.`;
 return `The correct answer is ${correct}. Review the ${q.concept_name||conceptName(q.concept_id)||'concept'} and try a similar example.`;
}

async function submitCurrent(){const selected=document.querySelector('input[name="answer"]:checked');if(!selected){showToast('Choose an answer before continuing.');return}const q=questions[index];const time=Math.max(1,Math.round((Date.now()-startedAt)/1000));try{const result=await submitAttempt(assessmentId,{student_id:studentId,question_id:q.id,answer:selected.value,time_taken:time});answers[index]={answer:selected.value,result,question:q};if(index<questions.length-1){index++;startedAt=Date.now();render()}else{await showResults()}}catch(e){el('attempt-feedback').innerHTML=`<div class="alert alert-danger" style="margin-top:16px">${esc(e.message)}</div>`}}

async function wrongResourceBlock(conceptId){
 if(!conceptId) return '';
 try{
   const data=await getResources(conceptId);
   const resources=data.resources||[];
   if(!resources.length) return '';
   return `<div class="recommended-result card" style="margin-top:18px"><div class="ai-label">Recommended resource</div><h2 style="margin:8px 0 5px">${esc(conceptName(conceptId))}</h2><p class="muted">These resources are specific to the concept identified from your responses.</p>${resources.map(r=>`<div class="resource-card"><div><div class="resource-type">${esc(r.resource_type||'video')}</div><h3>${esc(r.title)}</h3><p>${esc(r.description||'Concept-focused learning resource.')}</p></div><a class="btn btn-ghost" target="_blank" rel="noopener" href="${esc(r.url)}">Watch on YouTube</a></div>`).join('')}</div>`;
 }catch(_){return ''}
}

async function showResults(){
 const correct=answers.filter(a=>a.result.correct).length;
 const percent=Math.round((correct/questions.length)*100);
 const latest=answers.map(a=>a.result.adaptive_result).reverse().find(Boolean)||{};
 const ai=answers.map(a=>a.result.adaptive_result?.ai_analysis).reverse().find(Boolean);
 if(ai){localStorage.setItem('last_ai_analysis',JSON.stringify(ai));}
 const weak=latest.concept_id||conceptId||answers.find(a=>!a.result.correct)?.question?.concept_id||0;
 localStorage.setItem('last_concept_id',String(weak));localStorage.setItem('last_assessment_id',String(assessmentId));
 const resourceBlock=answers.some(a=>!a.result.correct)?await wrongResourceBlock(weak):''; if(assessment.assessment_type==='targeted'){const before=Number(localStorage.getItem('intervention_baseline_accuracy')||0);el('content').innerHTML=`<div class="card card-pad"><div class="eyebrow">Targeted practice complete</div><h1 style="margin:12px 0">Now let’s check whether the practice helped.</h1><p class="muted">You completed ${questions.length} targeted MCQs for <strong>${esc(conceptName(weak))}</strong>.</p><div class="grid-2" style="margin-top:25px"><div class="stat"><div class="stat-label">Before practice</div><div class="stat-value">${before}%</div></div><div class="stat"><div class="stat-label">Practice score</div><div class="stat-value">${percent}%</div></div></div>${renderAnswerReview()}${resourceBlock}<div class="next-step-card"><div class="eyebrow">What’s your next step?</div><h2>Choose how you want to continue.</h2><div class="hero-actions"><button class="btn btn-primary" id="reassess">Start targeted reassessment</button><a class="btn btn-secondary" href="progress.html?student_id=${studentId}">View progress</a></div></div></div>`;el('reassess').onclick=async()=>{try{const created=await createAssessment({student_id:studentId,topic_id:Number(assessment.topic_id),assessment_type:'reassessment'});location.href=`assessment.html?student_id=${studentId}&assessment_id=${created.assessment_id}&concept_id=${weak}`}catch(e){showToast(e.message)}};return}
 if(assessment.assessment_type==='reassessment'){const before=Number(localStorage.getItem('intervention_baseline_accuracy')||0);const afterProgress=await getStudentProgress(studentId);const afterConcept=(afterProgress.concept_progress||[]).find(c=>c.concept_id===weak);const after=Math.round(afterConcept?.accuracy||percent);const improved=after>before;const interventionId=Number(localStorage.getItem('active_intervention_id')||0);if(interventionId){try{await completeIntervention(interventionId,improved?'successful':'unsuccessful',`${conceptName(weak)} moved from ${before}% to ${after}% after targeted practice.`)}catch(_){} }el('content').innerHTML=`<div class="card card-pad"><div class="eyebrow">Targeted reassessment complete</div><h1 style="margin:12px 0">${improved?'You improved.':'More support is recommended.'}</h1><p class="muted">We compared performance on the same concept after targeted practice.</p><div class="grid-2" style="margin-top:25px"><div class="stat"><div class="stat-label">Before</div><div class="stat-value">${before}%</div></div><div class="stat"><div class="stat-label">After</div><div class="stat-value">${after}%</div></div></div>${renderAnswerReview()}${resourceBlock}<div class="alert ${improved?'alert-success':'alert-info'}" style="margin-top:18px"><strong>${improved?'Status: Improved':'Status: More support recommended'}</strong><div style="margin-top:5px">${improved?'Next action: continue to the next concept.':'Next action: request facilitator support.'}</div></div><div class="hero-actions"><a class="btn btn-primary" href="${improved?`progress.html?student_id=${studentId}`:`teacher.html?student_id=${studentId}&concept_id=${weak}`} ">${improved?'Continue learning':'Request facilitator support'}</a><a class="btn btn-secondary" href="facilitator.html">Facilitator view</a></div></div>`;return}
 const aiBlock=ai?`<div class="card card-pad" style="margin-top:14px;background:rgba(7,20,38,.96);color:white"><div class="ai-label">Jai Ganesh AI diagnostic insight</div><p class="ai-explanation">${esc(ai.explanation||'The AI agent returned no explanation.')}</p><div style="margin-top:10px;font-size:12px;color:#aebdcd">${esc(ai.error_type||'unknown')} · confidence ${Math.round((ai.confidence||0)*100)}%</div></div>`:'';
 el('content').innerHTML=`<div class="card card-pad"><div class="eyebrow">Assessment complete</div><h1 style="margin:12px 0 5px">${correct===questions.length?'Excellent work.':'Here is what to work on next.'}</h1><p class="muted">We checked every response and matched it to the specific learning domain behind the question.</p><div style="margin:28px 0"><div class="result-number">${correct}<span style="font-size:30px;color:#758398"> / ${questions.length}</span></div><div class="muted" style="margin-top:7px">${percent}% correct</div></div>${renderAnswerReview()}${resourceBlock}${weak?`<div class="glass-callout"><div class="ai-label">Specific domain needing attention</div><div class="domain-path">${esc(assessment.topic_name||'Mathematics')} <span>→</span> ${esc(conceptName(weak))}</div><h2 style="margin:8px 0 5px">${esc(conceptName(weak))}</h2><div class="muted">Current concept signal: ${Math.round(latest.accuracy||0)}%</div><p style="margin:16px 0 0">${esc(latest.reason||'The response pattern shows that this concept needs more focused practice.')}</p></div>`:''}${aiBlock}<div class="next-step-card"><div class="eyebrow">What’s your next step?</div><h2>${correct===questions.length?'Keep building from here.':'Strengthen the concept before moving on.'}</h2><p class="muted">Choose the next action based on the result above.</p><div class="hero-actions"><a class="btn btn-primary" href="diagnosis.html?student_id=${studentId}&concept_id=${weak}">${correct===questions.length?'Continue learning':'Practice this concept'}</a><a class="btn btn-secondary" href="progress.html?student_id=${studentId}">View progress</a></div></div></div>`
}

function renderAnswerReview(){
 const wrong=answers.filter(a=>!a.result.correct);
 if(!wrong.length)return `<div class="answer-review success-review"><strong>All answers are correct.</strong><p class="muted">There are no corrections to review for this session.</p></div>`;
 return `<div class="answer-review"><div class="section-title" style="margin-top:0"><h2>Review your incorrect answers</h2><span>${wrong.length} correction${wrong.length===1?'':'s'}</span></div>${wrong.map((item,i)=>{const correctAnswer=item.result.correct_answer||'See the correct answer below';const explanation=item.result.explanation||item.result.adaptive_result?.ai_analysis?.explanation||answerExplanation(item);return `<div class="answer-review-item"><div class="review-question"><span class="badge badge-danger">Incorrect</span><strong>${formatQuestionText(item.question?.question_text||'Question')}</strong></div><div class="review-row"><span>Your answer</span><strong class="wrong-answer">${formatQuestionText(item.answer)}</strong></div><div class="review-row"><span>Correct answer</span><strong class="correct-answer">${formatQuestionText(correctAnswer)}</strong></div><div class="review-explanation"><strong>Explanation</strong><p>${esc(explanation)}</p></div></div>`}).join('')}</div>`
}

(async()=>{el('content').innerHTML=loading('Loading assessment...');try{assessment=await getAssessment(assessmentId,conceptId||undefined);questions=assessment.questions||[];if(!questions.length)throw new Error('No questions are available for this assessment.');el('mode-label').textContent=(assessment.assessment_type||'assessment').replaceAll('_',' ');render()}catch(e){el('content').innerHTML=`<div class="alert alert-danger"><strong>Couldn't load the assessment.</strong><div>${esc(e.message)}</div></div>`}})();
