const studentId=getSelectedStudent();setStudent(studentId);const el=id=>document.getElementById(id);let classes=[];let selectedGrade=null;
function scheduleKey(grade){return `math_mcq_schedule_${grade}`}
function getSchedule(grade){try{return JSON.parse(localStorage.getItem(scheduleKey(grade))||'null')}catch(_){return null}}
function formatSchedule(value){if(!value)return '';const d=new Date(value);if(Number.isNaN(d.getTime()))return '';return d.toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}
function videoUrl(query){return `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`}
function progressBadge(p){const a=Math.round(p?.overall_progress||0);return a?`${a}% progress`:'Not started'}
function renderClass(c,p){const schedule=getSchedule(c.grade);const concepts=(p?.concept_progress||[]);const progressRows=concepts.map(x=>`<div class="mini-progress"><span>${esc(x.name)}</span><strong>${Math.round(x.accuracy)}%</strong></div>`).join('');return `<section class="card class-card"><div class="class-card-head"><div><div class="eyebrow">Class ${c.grade}</div><h2>${esc(c.title)}</h2></div><span class="badge badge-info">${progressBadge(p)}</span></div><div class="class-topics">${c.topics.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="video-list">${c.videos.map(v=>`<a class="video-card" href="${videoUrl(v.query)}" target="_blank" rel="noopener"><span class="video-icon">▶</span><span><strong>${esc(v.title)}</strong><small>Basic lesson</small></span></a>`).join('')}</div>${progressRows?`<div class="progress-stack"><div class="stat-label">Concept progress</div>${progressRows}</div>`:`<div class="empty mini-empty">No attempts yet. Your first MCQ session will establish the baseline.</div>`}<div class="class-actions"><button class="btn btn-primary schedule-btn" data-grade="${c.grade}">Schedule MCQ</button><button class="btn btn-secondary start-btn" data-grade="${c.grade}">Start MCQ now</button></div>${schedule?`<div class="scheduled-note"><strong>Scheduled:</strong> ${esc(formatSchedule(schedule.when))}<button class="btn btn-ghost start-scheduled" data-grade="${c.grade}">Start session</button></div>`:''}</section>`}
async function startSession(grade){const c=classes.find(x=>x.grade===grade);if(!c)return;try{const created=await createAssessment({student_id:studentId,topic_id:c.topic_id,assessment_type:'diagnostic'});localStorage.setItem('selected_math_grade',String(grade));location.href=`assessment.html?student_id=${studentId}&assessment_id=${created.assessment_id}`;}catch(e){showToast(e.message)}}
function openSchedule(grade){selectedGrade=grade;const c=classes.find(x=>x.grade===grade);el('schedule-label').textContent=`Schedule a ${c?.title||`Class ${grade} Mathematics`} MCQ session.`;const now=new Date();el('session-date').min=now.toISOString().slice(0,10);el('session-date').value=getSchedule(grade)?.when?.slice(0,10)||now.toISOString().slice(0,10);el('session-time').value=getSchedule(grade)?.when?.slice(11,16)||'18:00';const modal=el('schedule-modal');modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
function closeSchedule(){const modal=el('schedule-modal');modal.classList.remove('open');modal.setAttribute('aria-hidden','true');selectedGrade=null}
el('close-modal').onclick=closeSchedule;el('schedule-modal').addEventListener('click',e=>{if(e.target===el('schedule-modal'))closeSchedule()});el('save-schedule').onclick=()=>{if(!selectedGrade)return;const date=el('session-date').value,time=el('session-time').value;if(!date||!time){showToast('Choose a date and time.');return}localStorage.setItem(scheduleKey(selectedGrade),JSON.stringify({grade:selectedGrade,when:`${date}T${time}:00`}));closeSchedule();loadClasses()};
async function loadClasses(){el('classes').innerHTML=loading('Loading class curricula...');try{const data=await getMathClasses();classes=data.classes||[];const cards=await Promise.all(classes.map(async c=>{try{return [c,await getMathClassProgress(c.grade,studentId)]}catch(_){return [c,{overall_progress:0,concept_progress:[]}]} }));el('classes').innerHTML=cards.map(([c,p])=>renderClass(c,p)).join('');document.querySelectorAll('.schedule-btn').forEach(b=>b.onclick=()=>openSchedule(Number(b.dataset.grade)));document.querySelectorAll('.start-btn,.start-scheduled').forEach(b=>b.onclick=()=>startSession(Number(b.dataset.grade)))}catch(e){el('classes').innerHTML=`<div class="alert alert-danger"><strong>Couldn't load the Mathematics classes.</strong><div>${esc(e.message)}</div></div>`}}
loadClasses();
